name: Deploy to EC2 with Docker

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Connect to EC2 instance
        uses: appleboy/ssh-action@master
        with: 
          host: ${{ secrets.HOST_DNS }} 
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd ~/eduardoos.com_docker
            sudo git fetch origin
            sudo git reset --hard origin/main
            sudo docker build -t eoserver:latest . 
            sudo docker stop eoserver_container || true 
            sudo docker rm eoserver_container || true
            sudo docker run -d --name eoserver_container eoserver:latest

      - name: Wait for deployment
        run: |
          sleep 30
